---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: fedora27_workstation
    driver:
      box: 'generic/fedora27'
  - name: centos7_workstation
    driver:
      box: generic/centos7

suites:
  - name: default
    run_list:
      - recipe[vscode::default]
    verifier:
      inspec_tests:
        - test/default
